#!/bin/bash

# Prerequis drbd
dracut_install drbdadm drbdmeta drbdsetup vgchange sleep touch ping cut awk hostname ifconfig ip fdisk rsync wc
inst_dir /usr/local/drbd/var/lock/
inst_dir /usr/local/drbd/var/run/
inst /etc/init.d/drbd

inst_dir /etc/dracut-celeo
inst $moddir/boot.sh /sbin/boot.sh
inst "$moddir/exitBreakpoint.sh" /sbin/exitBreakpoint.sh
inst_simple "${moddir}/tiocsti" "/sbin/tiocsti"

# Execution script
inst_hook pre-mount 05 "$moddir/enableDrbd.sh"
