#!/bin/sh

# Sur CentOS 6 les modules sont dans /usr/share/
# Sur CentOS 7 les modules sont dans /usr/lib/
DRACUT_MODULE_DIR=/usr/share/dracut/modules.d
DRACUT_PREFIX=/usr/bin/

# Ajouter les commandes dont vous avez besoin dans le initramfs
# Les commandes deja ajoutées sont :
# 88snmp :  snmpd
# 89cryptSSH : pkill dropbear
# 90drbd : drbdadm drbdmeta drbdsetup vgchange 
# Pour les 3 : hostname ifconfig ip cut awk touch ping sleep
commandsToAdd='df netstat vi fdisk sfdisk rsync ssh sshpass'

# Partie reseau requise pour tous les modules
# Le nom de la carte reseau est indispensable pour charger les drivers dans le initramfs
# Le hostname est utile pour drbd, sans ce module il peut etre oublié
ip_master=192.168.0.10
ip_slave=192.168.0.10
netmask=255.255.255.0
gw=192.168.0.1
hostname_master=mycomputer.mynetwork
hostname_slave=mycomputer.mynetwork
devName=eth0

# Config DRBD
# Commandes requises pour l'installation des metadatas
commandsInstall='resize2fs bc which e2fsck'
ipVirtual=''    # Ip virtuelle des 2 serveurs
# master / slave
role=master
RESOURCE=r0
DRBD_ROOT='/dev/drbd0'
# Les disques LVM pour la création des metadatas (resize2fs sur les partitions)
lvm='/dev/mapper/disk1-root /dev/mapper/disk1-data'

# Modules a installer
# Merci de supprimer ceux dont vous n'avez pas besoin
# Modules existants : 
#
#   89cryptssh      |   90drbd
#   88snmp          |   91python
#
modToInstall='88snmp 89cryptssh 90drbd 91python'

#
modToUninstall='88snmp 89cryptssh 90drbd 91python'
# Autoriser l'authentification par mot de passe en SSH
# dans le initramfs (true/false)
# Sans mot de passe les clés sont recupérées dans /root/.ssh/authorized_keys (editer dans 89cryptssh/install)
allowPassword=true
