#!/bin/bash

# Commands
dracut_install hostname ifconfig ip cut awk touch ping sleep snmpd

# snmp files
inst_dir "/etc/init.d"
inst /etc/snmpd.conf
inst /etc/init.d/snmpd

# setup hook
inst_hook pre-mount 90 "$moddir/snmp-load.sh"

